version: 2

updates:
  # Python Backend
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    target-branch: develop
    reviewers:
      - CarineJackson1
      - sajanamhr21
    assignees:
      - CarineJackson1
    security-updates-only: true
    commit-message:
      prefix: "deps"
      include-scope: true
    rebase-strategy: auto
  ignore:
  - dependency-name: "pytest"
    update-types: ["version-update:semver-minor", "version-update:semver-patch"]
    
  # Node.js Frontend
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "06:00"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 5
    target-branch: develop
    reviewers:
      - CarineJackson1
      - sajanamhr21
    assignees:
      - CarineJackson1
    security-updates-only: true
    commit-message:
      prefix: "deps"
      include-scope: true
    rebase-strategy: auto

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 3
    target-branch: develop
    reviewers:
      - CarineJackson1
      - sajanamhr21
    assignees:
      - CarineJackson1
    security-updates-only: true
    commit-message:
      prefix: "deps"
      include-scope: true
    rebase-strategy: auto

  # Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "06:00"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 3
    target-branch: develop
    reviewers:
      - CarineJackson1
      - sajanamhr21
    assignees:
      - CarineJackson1
    security-updates-only: true
    commit-message:
      prefix: "deps"
      include-scope: true
    rebase-strategy: auto
