version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "CarineJackson1"     # Lead Security Reviewer
      - "sajanamhr21"
    assignees:
      - "CarineJackson1"     # Lead Security Reviewer
      - "sajanamhr21"

  # JavaScript / Node
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "CarineJackson1"
      - "sajanamhr21"
    assignees:
      - "CarineJackson1"
      - "sajanamhr21"

  # GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    reviewers:
      - "CarineJackson1"
      - "sajanamhr21"
    assignees:
      - "CarineJackson1"
      - "sajanamhr21"

  # Docker base images
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    reviewers:
      - "CarineJackson1"
      - "sajanamhr21"
    assignees:
      - "CarineJackson1"
      - "sajanamhr21"
