version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "CarineJackson1"
      - "sajanamhr21"
    assignees:
      - "CarineJackson1"
      - "sajanamhr21"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "CarineJackson1"
      - "sajanamhr21"
    assignees:
      - "CarineJackson1"
      - "sajanamhr21"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "CarineJackson1"
      - "sajanamhr21"
    assignees:
      - "CarineJackson1"
      - "sajanamhr21"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "CarineJackson1"
      - "sajanamhr21"
    assignees:
      - "CarineJackson1"
      - "sajanamhr21"
