name: Dependabot Auto-Merge
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Dependabot Auto Merge
        uses: fastify/github-action-merge-dependabot@v3.6.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
