"""Add enrollments table (FK to learner_profiles, courses)

Revision ID: 31cb80e4444b
Revises: 6c5bc9b95206
Create Date: 2025-08-11 01:30:23.076016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31cb80e4444b'
down_revision: Union[str, Sequence[str], None] = '6c5bc9b95206'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
