"""Add role to User model

Revision ID: 6f41a01df0aa
Revises: af04c1fc9f8e
Create Date: 2025-08-04 02:32:23.280013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f41a01df0aa'
down_revision: Union[str, Sequence[str], None] = 'af04c1fc9f8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.Enum('LEARNER', 'EMPLOYER', 'ADMIN', name='userrole'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
