rules:
  - id: no-console-log
    message: "Avoid using console.log in production code."
    severity: WARNING
    languages: [javascript, typescript]
    pattern: console.log(...)

  - id: no-eval
    message: "Avoid using eval() due to security risks."
    severity: ERROR
    languages: [javascript, typescript]
    pattern: eval(...)

  - id: react-dangerously-set-inner-html
    message: "Avoid dangerouslySetInnerHTML — it's an XSS risk."
    severity: ERROR
    languages: [javascript, typescript]
    pattern: dangerouslySetInnerHTML
    metadata:
      category: security
      technology: react

  - id: no-hardcoded-secrets
    message: "Potential hardcoded secret detected."
    severity: WARNING
    languages: [javascript, typescript]
    pattern-either:
      - pattern: const $VAR = "$SECRET"
      - pattern: let $VAR = "$SECRET"
    metadata:
      category: security
      technology: javascript

  - id: fetch-no-https
    message: "Avoid unencrypted API calls — use HTTPS."
    severity: WARNING
    languages: [javascript, typescript]
    pattern: fetch("http://...")

  - id: insecure-random
    message: "Use a cryptographically secure RNG, not Math.random for secrets or tokens."
    severity: WARNING
    languages: [javascript, typescript]
    pattern: Math.random()
