rules:
  - id: react-dangerously-set-inner-html
    message: "Avoid using dangerouslySetInnerHTML to prevent XSS vulnerabilities"
    severity: ERROR
    languages: [javascript, typescript, tsx]
    pattern: $X.dangerouslySetInnerHTML = $Y

  - id: no-eval-js
    message: "Avoid use of eval() due to security risk"
    severity: ERROR
    languages: [javascript, typescript]
    pattern: eval(...)

  - id: no-inline-js
    message: "Avoid inline JavaScript event handlers in JSX"
    severity: WARNING
    languages: [jsx, tsx]
    pattern: |
      <div onClick={$EVENT}>

  - id: hardcoded-secret-js
    message: "Potential hardcoded secret detected"
    severity: WARNING
    languages: [javascript, typescript]
    pattern-either:
      - pattern: API_KEY = "..."
      - pattern: PASSWORD = "..."
      - pattern: SECRET = "..."
      - pattern: TOKEN = "..."
