name: Bandit Security Scan (Fail on High Only)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  bandit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Bandit
        run: |
          python -m pip install --upgrade pip
          pip install bandit

      - name: Run Bandit and save JSON report
        run: bandit -r . -f json -o bandit-report.json

      - name: Check for high severity issues
        run: |
          python - <<EOF
          import json, sys

          with open("bandit-report.json") as f:
              data = json.load(f)

          high_issues = [
              issue for issue in data.get("results", [])
              if issue.get("issue_severity", "").lower() == "high"
          ]

          print(f"Found {len(high_issues)} high-severity issue(s).")

          if high_issues:
              for issue in high_issues:
                  print(f"- {issue['filename']}:{issue['line_number']} - {issue['issue_text']}")
              sys.exit(1)
          else:
              print("No high-severity issues found.")
          EOF
