name: Bandit Python Security Lint
on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
jobs:
  bandit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Bandit
        run: pip install bandit
      - name: Run Bandit
        run: bandit -r .
