name: OWASP ZAP Scan

on:
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run OWASP ZAP baseline scan
        run: docker run -v $(pwd):/zap/wrk:rw -t owasp/zap2docker-weekly zap-baseline.py -t https://your-app-url.com
