name: OWASP ZAP Scan

on:
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run OWASP ZAP baseline scan
        run: |
          docker run \
            -v $(pwd):/zap/wrk:rw \
            -t ghcr.io/zaproxy/zap-stable \
            zap-baseline.py \
            -t https://secdevops-demo-frontend.onrender.com \
            -r zap_report.html

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v3
        with:
          name: zap-report
          path: zap_report.html
