name: 🛡️ Semgrep Security Scan

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  semgrep-frontend:
    name: Semgrep Frontend Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python for Semgrep
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep frontend rules
        run: semgrep --config .github/.semgrep/frontend-rules.yml frontend --error

  semgrep-backend:
    name: Semgrep Backend Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python for Semgrep
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep backend rules
        run: semgrep --config .github/.semgrep/backend-rules.yml backend --error
