name: Semgrep - Frontend Custom Rules

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Semgrep on frontend with custom rules
        uses: returntocorp/semgrep-action@v1
        with:
          config: ./.semgrep/frontend-rules.yml
          paths: |
            frontend
