name: Semgrep - Frontend and Backend Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  semgrep-frontend:
    name: Frontend Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Semgrep on frontend with custom rules
        uses: returntocorp/semgrep-action@v1
        with:
          config: ./.semgrep/frontend-rules.yml
          paths: |
            frontend

  semgrep-backend:
    name: Backend Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Semgrep on backend with custom rules
        uses: returntocorp/semgrep-action@v1
        with:
          config: ./.semgrep/backend-rules.yml
          paths: |
            backend
