name: Semgrep Security Scan

on:
  push:
    paths:
      - 'frontend/**'
      - 'backend/**'
  pull_request:
    paths:
      - 'frontend/**'
      - 'backend/**'
  workflow_dispatch:

jobs:
  semgrep-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Semgrep on Frontend
        uses: returntocorp/semgrep-action@v1
        with:
          config: .semgrep/frontend-rules.yml
          paths: frontend/

      - name: Run Semgrep on Backend
        uses: returntocorp/semgrep-action@v1
        with:
          config: .semgrep/backend-rules.yml
          paths: backend/
