name: Snyk Security Scan
on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: snyk/actions/setup@master
      - name: Run Snyk to check for vulnerabilities
        run: snyk test --all-projects
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
